server:
  port: 5050


#logging:
#  level:
#    root: DEBUG

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/Person
    username: postgres
    password:

  jpa:
    show-sql: false
    hibernate:
      ddl-auto: update





